### ISSUE TITLE
Cosmos emulator not starting in GitHub Runner ubuntu 20.04 and 22.04

### ISSUE THREAD

**Issue by DrDonoso** [Azure/azure-cosmos-db-emulator-docker#64] opened 2023-01-20 15:15 UTC
Right now, the docker image cannot run in a GitHub action with **ubuntu 20.04** and **ubuntu 22.04**. It doesn't initialize for some reason. The logs only says:

``` txt
This is an evaluation version.  There are [113] days left in the evaluation period.
Shutting Down
Shut Down
```

I created a public repository to show the problem. There is only a docker-compose.yml with a cosmosdb service and a github workflow that up services, sleep 60s and check the logs of the container. So you can see the action log.
There we can see that only works in **Ubuntu 18.04**.

https://github.com/DrDonoso/CosmosDBDockerGHA/actions/runs/3966547297/jobs/6797477850

Thank you in advance.

**Comment by waszak** [comment] 2023-01-26 22:40
Its this issue https://github.com/Azure/azure-cosmos-db-emulator-docker/issues/45
You can try ping someone to give ETA i tried but didn't get one yet

**Comment by iarovyi** [comment] 2023-04-07 10:40
I got exactly the same problem on github action on `ubuntu-latest`. My step:
```yaml
  - name: Experiment
	run: |
	  docker run `
	  --publish 8081:8081 `
	  --detach `
	  --memory 3g --cpus=2.0 `
	  --name=test-linux-emulator `
	  --env AZURE_COSMOS_EMULATOR_PARTITION_COUNT=1 `
	  --env AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=false `
	  --env AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1 `
	  --env EMULATOR_OTHER_ARGS=/startwprtraces `
	  mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
	  Write-Host "Waiting"
	  Start-Sleep -Seconds 60
	  Write-Host "CONTAINER LOGS:"
	  docker logs test-linux-emulator
	  Write-Host "GATEWAY LOGS:"
	  docker container cp test-linux-emulator:/tmp/cosmos/appdata/gateway.log ./gateway.log
	  cat ./gateway.log
	  Invoke-WebRequest  -UseBasicParsing -Uri https://host.docker.internal:8081/_explorer/index.html
	shell: pwsh
```

**Comment by kf6kjg** [comment] 2023-04-17 20:54
This is a duplicate of #56

**Comment by sajeetharan** [comment] 2024-01-30 10:19
closing as a duplicate of https://github.com/Azure/azure-cosmos-db-emulator-docker/issues/56

**Closed by sajeetharan** 2024-01-30 10:19 UTC

**Comment by niteshvijay1995** [comment] 2024-05-27 15:01
Use --tty argument with docker run

 ```
- name: Experiment
	run: |
	  docker run `
	  --publish 8081:8081 `
	  --detach `
	  --memory 3g --cpus=2.0 `
	  --name=test-linux-emulator `
	  --env AZURE_COSMOS_EMULATOR_PARTITION_COUNT=1 `
	  --env AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=false `
	  --env AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1 `
	  --tty `
	  mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
	  Write-Host "Waiting"
	  Start-Sleep -Seconds 60
	  Write-Host "CONTAINER LOGS:"
	  docker logs test-linux-emulator
	  Write-Host "GATEWAY LOGS:"
	  docker container cp test-linux-emulator:/tmp/cosmos/appdata/gateway.log ./gateway.log
	  cat ./gateway.log
	  Invoke-WebRequest  -UseBasicParsing -Uri https://host.docker.internal:8081/_explorer/index.html
	shell: pwsh
```
